name: ssp_egypt_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.9.2
  - xlsxwriter=3.1.1
  - ipykernel=6.29.5
  - pip
  - pip:
      - git+https://github.com/jcsyme/sisepuede.git@1d097d48b6593de248c972a7d220c54d9bef71ac
      - ssp-transformations-handler==0.1.8
